### ISSUE TITLE
找不到檔案

### ISSUE THREAD

**Issue by b856741** [wenzhu23333/Federated-Learning#1]
你好，我運行了"python main.py --dataset mnist --iid --num_channels 1 --model cnn --epochs 50 --gpu 0"
他最後回傳錯誤
Traceback (most recent call last):
  File "main.py", line 139, in <module>
    accfile = open('./log/accfile_fed_{}_{}_{}_iid{}.dat'.
FileNotFoundError: [Errno 2] No such file or directory: './log/accfile_fed_mnist_cnn_50_iidTrue.dat'
請問是否有解方?謝謝

**Comment by wenzhu23333** [comment]
已修复（Fixed）
