### ISSUE TITLE
nonIID下的MNIST-CNN

### ISSUE THREAD

**Issue by b856741** [wenzhu23333/Federated-Learning#2]
你好
我執行python main.py --dataset mnist --num_channels 1 --model cnn --epochs 50 --gpu 0
發現testing accuracy 都非常低，維持在固定數字9.80的也有
哪裡有出錯嗎?(mlp沒發現這現象)

**Comment by wenzhu23333** [comment]
调整一下learning rate，加一个参数 --lr 0.01，learning rate现在默认为1，对CNN来说太大了。

**Comment by wenzhu23333** [comment]
已修正命令及默认值。
