### ISSUE TITLE
cifar accuracy?

### ISSUE THREAD

**Issue by b856741** [wenzhu23333/Federated-Learning#3]
你好
當我依循指令 "python main.py --dataset cifar --iid --num_channels 3 --model cnn --epochs 50 --gpu 0 --lr 0.02"
所得出的準確率都不到40%
mlp模型更不到30%
是否有需調整的因素?

**Comment by wenzhu23333** [comment]
50 epochs比较少，跑的轮数需要再多点，可能需要1000轮左右
