### ISSUE TITLE
model aggregate?

### ISSUE THREAD

**Issue by b856741** [wenzhu23333/Federated-Learning#4]
你好，請問這邊所用的模型聚合的方法為何?
因為似乎沒有看到有關模型聚合的相關參數

**Comment by realcly** [comment]
> 你好，請問這邊所用的模型聚合的方法為何? 因為似乎沒有看到有關模型聚合的相關參數

FedAvg，应该在Federated-Learning/models/Fed.py中有所体现。

**Comment by wenzhu23333** [comment]
在models的Fed.py里面，只是简单的将模型平均了一下，可以在这里修改，如果改成按照数据集加权平均也可以。
